### ISSUE TITLE
Question about contributor recognition after PR merge

### ISSUE THREAD

**Issue by intls** [GaiaNet-AI/docs#64]
Hi team! @alabulei1 ,

Thank you for merging my PR #60 ! However, I noticed that my contribution does not appear under the "Contributors" section of the repository. Could you please clarify if there is anything else I need to do to be recognized as a contributor?

Thank you for your assistance!

**Comment by juntao** [comment]
It is updated by GitHub. We do not know how they decide to display names in that section. Thanks.

**Comment by intls** [comment]
> It is updated by GitHub. We do not know how they decide to display names in that section. Thanks.

Thanks for answer.
